kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: paymentservice
spec:
  ports:
    - port: 8081                               # Containers port exposed
      targetPort: 8081                     # Pods port
  selector:
    myvalue: payment-service                    
  type: ClusterIP

