apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-payment-deployment
spec:
  selector:
    matchLabels:
      run: my-payment
  replicas: 2
  template:
    metadata:
      name: my-payment-pod
      labels:
        run: my-payment
    spec:
      containers:
      - name: payment01
        image: chetangsanghi/kube-payment-service:0.1
        ports:
        - containerPort: 8081
        resources:
          limits: 
            cpu: 500m
          requests:
            cpu: 200m
